[[call]]
call_type = "deploy"
class_hash = "0x33d8074c4d5283cbad5d8b6c8d7b261b9bf11a56f6195f0c65f49f45a289c6b"
inputs = [
    "393402133025997798000961",
    "0",
    "0x5a6c0f84179d695f0b598cc5d0be50421c247da95cfe63e4cd66fc27f32dfe6"
    # "0x07e4986c03d8a4fea74db3fa5a31467bea98d622570ae9daa74a94fb8dc71817"
]
id = "satellite"
unique = false

[[call]]
call_type = "invoke"
contract_address = "satellite"
function = "setL1MessageSender"
inputs = ["0x0"]

[[call]]
call_type = "deploy"
class_hash = "0x1a3b5f5e4d864a1a4f5ea6f63d65a6d7efbad80ef5a0ed2a5f99bff3f2a132"
inputs = []
id = "evm-growing-inner"
unique = false

[[call]]
call_type = "invoke"
contract_address = "satellite"
function = "_setGrowingInnerContractAddress"
inputs = ["evm-growing-inner"]
