[package]
name = "storage_proofs"
version = "0.1.0"
edition = "2023_11"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = "2.11.4"
cairo_lib = { git = "https://github.com/HerodotusDev/cairo-lib.git", branch = "cairo_2.11" }
openzeppelin = "0.20.0"
integrity = { git = "https://github.com/HerodotusDev/integrity.git" }

[dev-dependencies]
snforge_std = "0.52.0"
assert_macros = "2.11.4"

[[target.starknet-contract]]
sierra = true

[scripts]
test = "snforge test"
