[[call]]
call_type = "invoke"
contract_address = "0x06d523b16d7f6f71e250fc7f8d95df3e9e987a120878ea1a25ff312d92f42c8e"
function = "upgrade"
inputs = ["0x33d8074c4d5283cbad5d8b6c8d7b261b9bf11a56f6195f0c65f49f45a289c6b"]
